# Site settings
baseurl = "http://example.org" #without ending slash
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Kappa - Teeworlds Clan"

[params]
    
    # Images settings
    # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
    # You may place your images in corresponding folders and then set only filenames below to
    # change page's appearance
    
    favicon = "favicon.ico"
    appletouchicon = "apple-touch-icon-precomposed.png"
    background = "bg1.jpg"
    avatar = "jane.jpg"

  # Custom styling
  # To customize the styling of this theme, uncomment and edit the following line to point 
  # to your site's css in the assets/ directory. 

  # custom_css = ["css/foo.bar"]
    
    # Personal settings
    
    name = "Kappa Kopperfield"
    position = "Teeworlds Clan"
        
    # Footer settings
    [params.footer]
        copyright = "KappaKopperfield"
        
